# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dbs-performance-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mariadb
      - mysql
    networks:
      - custom-network    
    ports:
      - 5192:5192

  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - custom-network

  mariadb:
    image: mariadb:10.7.4
    environment:
      - MARIADB_ROOT_PASSWORD=mysecretpassword
    networks:
      - custom-network

  mysql:
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      - MYSQL_TCP_PORT=3307
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge